---
# Only use to pin to specific version
# factorio_version: ''

# Server configuration. consult the example json files for reference
factorio_default_config: &factorio_defaults
  save: 'gamesave'
  port: 34197

  mapgen: '{{ lookup("file", "files/map-gen-settings.example.json") | from_json }}'
  map: '{{ lookup("file", "files/map-settings.example.json") | from_json }}'
  server: '{{ lookup("file", "files/server-settings.example.json") | from_json }}'

factorio_servers:
  myserver:
    <<: *factorio_defaults
    save: 'gamesave'
  myserver_2:
    <<: *factorio_defaults
    save: 'gamesave2'
    port: 34198

factorio_admins: []

